### ISSUE TITLE
Transaction list for small_transactions.txt

### ISSUE THREAD

**Issue by minj131** [laboon/CS1699_Fall2018#37]
In the project description:
```
CANDIDATE BLOCK = Hash 00018802ad03e606db9d240eb3caa1a0d5f0ea7121072d5e92d242a4491d3205
---
0002b89b85e814a5b390f73d6da47f9744666796c69891157e50787e666594fc
16
1539045855611
10000
  Ro
4814ffcf04b5a49e9fc8e5d2be73923ec5b0b85e7352de65b894087b5f6a6f61
1Khee1UxMsrvhN2tZCGZa4tZC41kumYNr9>100,1Khee1UxMsrvhN2tZCGZa4tZC41kumYNr9>100,1Khee1UxMsrvhN2tZCGZa4tZC41kumYNr9>100;14P72s4mMcKqs3SDCsX3h7qh8526gC8dve>225,13QxtTz5FnTsg8VyZRg8hPgunC8VW8nz2i>30,1BfTK9ftgnaXgK3Wj17Da4J9Mw5KmzLzfe>30
19DbSByZsVJiARvXTF5krFuuEYusZKobT>100;17Nc9KSSuULvTnoba7MdprY5vnDtLWW3DS>89,18RENfoKJsV5XfH5b2vu4tNGMRfmHnXCHn>6
1NQrwAQrvFgKC4jt1whz2iaaAsjzxSLgbd>20,18soCPK9vE9oPesxSKKvupYo7Yi9rnGQus>10;1HkwVee51yb1z3ks5v9yj4K1QZQuJhjuHG>26
1BRsmBq9a4WraBokXZcZcd8vgcaTtdiTFc>5;1ErF9Q3z82PTpzTBQ2wvjQQ7j7UNGjtMuJ>3,19xiyFGHNujpA6PiWmsmrm8TmsvkVq8G5a>2
;1333dGpHU6gQShR596zbKHXEeSihdtoyLb>74
```

The last transaction nets 0 coins in fees, as in there are 5 coins going in and 5 coins going out. In this case, would we rather care about creating a block that has as many transactions as possible or dropping the last transaction altogether since there's no "incentive" for including that in our block?

**Comment by laboon** [comment]
Great question!  In this case, it doesn't matter whether or not we include it.  In "real life", miners will occasionally take in 0-fee tx's simply to try out different combinations of tx's in order to make a hash below the target.  I would say err on the side of including tx's,  but I won't take any points off for either algorithm you use ("get as many tx's as possible" vs "ignore the freeloaders")

+0.25 EC

Please close this issue if that answers your question or leave it open if you have further comments/questions.
