### ISSUE TITLE
Lecture 5 - Slide 24, Slight typo in deliverable1.md

### ISSUE THREAD

**Issue by RamIyer1998** [laboon/CS1699_Fall2018#4]
Lecture 5: Slide 24 - We're discussing ScroogeCoin at this point in the lecture but the slide says that Alice knows pk_Goofy (I know you caught this in class, but just wanted to bring it up again in case you forgot).

deliverable1.md - Very slight typo, but in Tip 5, "everything" is spelled as "everyything."

Thanks!

**Comment by laboon** [comment]
Whoops, forgot to update the slide!  And thanks for catching the other typo as well.

Fixed in commit a19e2b1013cfbe61bdd5179c83e34570fa446b7e

Can you let me know your real name (either on here or by email) so that I can give you your bonus points? +0.5 for the slide typo, +0.1 for the deliverable one
