### ISSUE TITLE
Lecture 13 Question

### ISSUE THREAD

**Issue by koseoyoung** [laboon/CS1699_Fall2018#50]
I have a question in the lecture 13! 
To mitigate the linking risk, I learned that it is good to change the address frequently and not to re-use the address. 
Then does it mean that the secret key also has to be changed? How to handle the secret key whenever we change the address? 

Thank you!

**Comment by laboon** [comment]
A wallet can contain multiple keys for multiple addresses, and store all of these addresses/keys in a way that is transparent to the user.  These can be linked together and generated deterministically in order to be able to produce an inexhaustible number of addresses from one seed, e.g. a very simplified version SEED -> SHA256(SEED) -> NEW_ADDRESS -> SHA256(NEW_ADDRESS) -> NEW_ADDRESS_2 -> SHA256(NEW_ADDRESS_2) -> NEW_ADDRESS_3 -> etc.

See this article https://en.bitcoin.it/wiki/Deterministic_wallet for more details on how exactly they work.

**Comment by koseoyoung** [comment]
Thank you !! :)
